# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Tagged Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
        cache-dependency-path: "**/go.sum"

    - name: Build promdump
      working-directory: ./promdump
      # github.ref_name is the tag or branch name
      run: |
        go get
        go build -ldflags=" -X 'main.AppVersion=${{ github.ref_name }}' -X 'main.CommitHash=$(git rev-parse HEAD)' -X 'main.BuildTime=$(date -Iseconds)'" -v ./...

    - name: Test promdump
      working-directory: ./promdump
      run: go test -v ./...

    - name: Compress artifacts
      run: |
        gzip promdump/promdump

    - name: Upload promdump
      uses: actions/upload-artifact@v4
      with:
        name: promdump
        path: promdump/promdump.gz